import os
from sys import argv
import sys
from bs4 import BeautifulSoup
from datetime import datetime
class prompt:
    def __init__(self, message):
        self.confirm = None
        prompt_running = True
        while prompt_running:
            confirmation = input(message+' [y/n]: ').lower().strip(' ')
            if confirmation == 'y':
                self.confirm = True
                prompt_running = False
            elif confirmation == 'n':
                self.confirm = False
                prompt_running = False
            else:
                print('[A[2K\r[1;33mplease confirm...[0m')

        

stats_file = str("./status.xml")
art_directory = str("./asciiArt")
prompts_answer = None

for i in range(len(argv)):
    if argv[i] == '--stats_file':
        try:
            stats_file=argv[i+1]
        except IndexError:
            raise IndexError('[1;31m--stats_file: no file provided[m')
    elif argv[i] == '--art_directory':
        try:
            art_directory=argv[i+1]
        except IndexError:
            raise IndexError('[1;31m--art_directory: no directory provided')

if "-y" in argv:
    prompts_answer = True
elif "-n" in argv:
    prompts_answer = False

if os.path.exists(stats_file):
    if prompts_answer == None:
        stats_write_ask = prompt(stats_file+': [1;33mthis file already exists, overwrite?[m')
        stats_write_check = stats_write_ask.confirm
    elif prompts_answer == True:
        stats_write_check = True
    elif prompts_answer == False:
        stats_write_check = False

    if stats_write_check == True:
        print('[A[2K\r'+stats_file+': [1:32moverwriting...[m')
    else:
        print('[A[2K\r[1;30mcancelled.[m')
        sys.exit(0)

if not art_directory.endswith('/'):
    art_directory = art_directory + '/'

if os.path.isdir(art_directory):
    art_list = []
    art_date = 0.0
    latest_art = ''
    for item in os.listdir(art_directory):
        if item.endswith('.txt'):
            art_list.append(str(art_directory.replace('./','')+item))
            if os.path.getmtime(str(art_directory+item)) > art_date:
                art_date = os.path.getmtime(str(art_directory+item))
                latest_art = str(art_directory.replace('./','')+item)

    with open(stats_file, 'w') as stats:
        stats.write('<!--Revision from '+datetime.today().strftime('%m.%d.%Y')+'\n')
        stats.write("    Autogenerated by FartLib's art updater-->\n")
        stats.write("<!--Original Revision from 12.17.2024\nCreated 2024 mangolover1899(Yeetsup)\nThis document is free to copy, modify and do with\nwhat you please, no conditions.-->\n\n")
        stats.write('<status>\n\n')
        stats.write('   <asciiArtsNames>\n')
        for art in art_list:
            stats.write('       <name>'+art+'</name>\n')
        stats.write('   </asciiArtsNames>\n\n')
        stats.write('   <latestText>'+latest_art+'</latestText>\n\n')
        stats.write('</status>')


