import os
import sys
pwd = os.getcwd()
customPath = input('Updating Art in '+pwd+'...\nWould you like to use a different directory instead? \n[Enter Directory or Press <ENTER> to Continue]:\n')
if customPath.strip(' ') == '':
    customPath = pwd
if not customPath.endswith('/'):
    customPath = customPath + '/'
if not os.path.exists(customPath):
    raise FileNotFoundError(customPath+': This Directory does not Exist.')

print('Writing to '+customPath+'status.xml...')

try:
    open(customPath+'status.xml', 'x')
except FileExistsError:
    overwrite = input(customPath+'status.xml: This File already exists, Overwrite?\n[Y/n]: ')
    overwrite = overwrite.strip(' ').lower()
    if overwrite == '' or overwrite == 'y':
        print('Overwriting...')
    else:
        print('Cancelled.')
        sys.exit(0)

    
with open(customPath+'status.xml', 'w') as status:
    status.write("<!--STATUS.XML AUTOMATICALLY GENERATED BY ASCIIFARTER ART UPDATER.\nAsciiFarter Copyright (c) 2026 Mangolover1899. Licensed under GPL-3.0.-->\n")
    status.write('\n<status>\n')
    status.write('  <asciiArtsNames>\n')
    art_list = os.listdir(customPath)
    for art in art_list:
        if art.endswith('.txt'):
            status.write('      <name>')
            status.write(os.path.basename(os.path.dirname(customPath))+'/'+art)
            status.write('</name>\n')
    status.write('  </asciiArtsNames>\n')
    newest_art_modified = 0.0
    newest_art = ''
    for file in art_list:
       if os.path.getmtime(customPath+file) > newest_art_modified:
           if file.endswith('.txt'):
               newest_art = os.path.basename(os.path.dirname(customPath))+'/'+file
               newest_art_modified = os.path.getmtime(customPath+file)   
    status.write('  <newestAscii>'+newest_art+'</newestAscii>\n')
    status.write('</status>')
